# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MyInsta' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MyInsta

  pod 'NCMB', :git => 'https://github.com/NIFTYCloud-mbaas/ncmb_ios.git', :branch => 'develop'
  pod 'NYXImagesKit'
  pod 'UITextView+Placeholder'
  pod 'SVProgressHUD'
  pod 'Kingfisher'
  pod 'SwiftDate', '~> 6.3.1'
  pod 'CropViewController'
  pod 'GoogleMaps', '4.1.0'
  pod 'GooglePlaces', '4.1.0'

end
# MyInsta
